name = "portfolio-photos-worker"
main = "src/index.ts"
compatibility_date = "2026-06-02"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-photos-db"
database_id = "8d313ffe-045b-4979-8331-48f1b8b700c9"

[vars]
CORS_ORIGIN = "https://juanr.photos, https://admin.juanr.photos, https://portfolio-photos.pages.dev, https://portfolio-admin-3du.pages.dev"
